---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vna-api-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: vna-api-app
  template:
    metadata:
      labels:
        app: vna-api-app
    spec:
      containers:
        - name: vna-api-app
          image: lumberjoc/vna-api-app:27
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
