---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volley-node-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: volley-node-app
  template:
    metadata:
      labels:
        app: volley-node-app
    spec:
      containers:
        - name: volley-node-app
          image: lumberjoc/volley-node-app:25
          ports:
            - name: http
              containerPort: 9090
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
